version: '3.9'

services:
  api:
    build:
      context: .
      target: api
    restart: always
    ports:
      - 7000:7000
    environment:
      - NODE_ENV=production

  api-live:
    build:
      context: .
      target: api-live
    restart: always
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=production

  web:
    build:
      context: .
      target: web
    restart: always
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 5000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - api-live
