version: '3.9'

services:
  api:
    build:
      context: .
      target: api
    restart: always
    ports:
      - 7000:7000
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres

  api-live:
    build:
      context: .
      target: api-live
    restart: always
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres

  web:
    build:
      context: .
      target: web
    restart: always
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nifty_db
    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - api-live
