version: '3.9'

services:
  app:
    build:
      context: ./
      target: app
      args:
        - DOPPLER_CLIENT_TOKEN=${DOPPLER_CLIENT_TOKEN}
    restart: always
    expose:
      - 8080
      - 7000
      - 3000
    environment:
      - NODE_ENV=production
      - DOPPLER_API_TOKEN=${DOPPLER_API_TOKEN}
      - DOPPLER_CLIENT_TOKEN=${DOPPLER_CLIENT_TOKEN}
    depends_on:
      - mongo
      - redis

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '${NGINX_PORT:-80}:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  mongo:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: nifty
    ports:
      - '${MONGO_PORT:-27017}:27017'
    volumes:
      - mongo_data:/data/db
    command: mongod --bind_ip_all --auth

  redis:
    image: redis:latest
    restart: always
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
