version: '3.9'

services:
  api:
    build:
      context: ./
      target: api
      args:
        - DOPPLER_TOKEN=${DOPPLER_API_TOKEN}
    restart: always
    expose:
      - 7000
    environment:
      - NODE_ENV=production
      - DOPPLER_TOKEN=${DOPPLER_API_TOKEN}

  api-live:
    build:
      context: ./
      target: api-live
      args:
        - DOPPLER_TOKEN=${DOPPLER_API_LIVE_TOKEN}
    restart: always
    expose:
      - 8080
    environment:
      - NODE_ENV=production
      - DOPPLER_TOKEN=${DOPPLER_API_LIVE_TOKEN}
