version: '3.9'

services:
  mongo:
    image: mongo:4.4
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

  redis:
    ports:
      - "${REDIS_PORT:-6379}:6379"
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
