version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT:-3001}:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - api

  client:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP_TARGET: client-dev
    environment:
      DOPPLER_TOKEN: ${DOPPLER_TOKEN_CLIENT}
      API_BASE_URL: http://api:${API_PORT:-7000}
    expose:
      - "${CLIENT_PORT:-3000}"
    depends_on:
      - api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP_TARGET: api-dev
    environment:
      DOPPLER_TOKEN: ${DOPPLER_TOKEN_API}
    expose:
      - "${API_PORT:-7000}"
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:4.4
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

  redis:
    ports:
      - "${REDIS_PORT:-6379}:6379"
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
