version: '3.9'

services:
  api:
    build:
      context: ./
      target: api
    restart: always
    expose:
      - 7000
    environment:
      - NODE_ENV=production
      - DOPPLER_TOKEN=${DOPPLER_API_TOKEN}

  api-live:
    build:
      context: ./
      target: api-live
    restart: always
    expose:
      - 8080
    environment:
      - NODE_ENV=production
      - DOPPLER_TOKEN=${DOPPLER_API_LIVE_TOKEN}

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - api-live
