#!/bin/bash
# This script checks for Python and Doppler CLI installations and installs them if necessary.
# It also runs `yarn install --no-interactive`.

# Exit the script if any command fails
set -e

# Update package lists
echo "Updating package lists..."
sudo yum update -y

# Check for Python installation
echo "Checking for Python installation..."
python_installed=$(which python3)

if [ -z "$python_installed" ]; then
  # Install Python if not found
  echo "Python not found, installing..."
  sudo yum install -y python3
else
  echo "Python already installed."
fi

# Check for Yarn installation
echo "Checking for Yarn installation..."
yarn_installed=$(which yarn)

if [ -z "$yarn_installed" ]; then
  # Install Yarn if not found
  echo "Yarn not found, installing..."
  curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
  sudo yum install -y yarn
else
  echo "Yarn already installed."
fi

# Check for Doppler CLI installation
echo "Checking for Doppler CLI installation..."
doppler_installed=$(which doppler)

if [ -z "$doppler_installed" ]; then
  # Install Doppler CLI if not found
  echo "Doppler CLI not found, installing..."
  curl -Ls https://cli.doppler.com/install.sh | sudo sh
else
  echo "Doppler CLI already installed."
fi


# install docker and docker-compose
echo "Installing docker and docker-compose..."
sudo yum install -y docker
sudo usermod -a -G docker ec2-user
id ec2-user
newgrp docker
wget https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) 
sudo mv docker-compose-$(uname -s)-$(uname -m) /usr/local/bin/docker-compose
sudo chmod -v +x /usr/local/bin/docker-compose
# start docker
sudo service docker start

# Run yarn install
echo "Running 'yarn install --no-interactive'..."
cd /home/ec2-user/app 
yarn cache clean
yarn install --no-interactive
(cd ./apps/client && yarn build)

echo "Script completed."
