#!/bin/bash
# This script checks for Python, Doppler CLI, pm2 installations and installs them if necessary.
# It also runs `yarn install --no-interactive`.

# Exit the script if any command fails
set -e

# Update package lists
echo "Updating package lists..."
sudo yum update -y

# Install docker and docker-compose
echo "Installing docker and docker-compose..."
sudo yum install -y docker
sudo usermod -a -G docker ec2-user
id ec2-user
newgrp docker
sudo wget -O /usr/local/bin/docker-compose https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)
sudo chmod -v +x /usr/local/bin/docker-compose
# start docker
sudo service docker start

# delete all docker containers
docker system prune -a --volumes --force

echo "Dependencies completed."
