#!/bin/bash
# This script starts the Nginx server with a given configuration file
# and starts all applications

nginx_conf_file="/home/ec2-user/note-hive/conf/nginx.conf"

if ! command -v nginx &> /dev/null
then
    echo "Nginx is not installed. Installing now..."
    sudo yum install -y amazon-linux-extras
    sudo amazon-linux-extras install nginx1.12 -y
    sudo systemctl enable nginx
    echo "Nginx has been installed."
else
    echo "Nginx is already installed."
fi

# Start Nginx with the specified configuration file
echo "Starting Nginx with the provided configuration file..."
sudo nginx -c $nginx_conf_file

# Check if Nginx started successfully
if [ $? -eq 0 ]; then
  echo "Nginx started successfully."
else
  echo "Failed to start Nginx."
  exit 1
fi

# Setup doppler
echo "Setting up Doppler..."
./setup_doppler.sh

# Start all applications
echo "Starting all applications..."
yarn apps:start &

