#!/usr/bin/env bash

set -euo pipefail

REGION="${1:-us-west-1}"
DOPPLER_API_PARAM="${2:-DOPPLER_API_STAGING}"
DOPPLER_CLIENT_PARAM="${3:-DOPPLER_CLIENT_STAGING}"
docker_compose_path="${4:-/home/ec2-user/app/docker-compose.yml}"

export DOPPLER_CLIENT_TOKEN=$(aws ssm get-parameters --region $REGION --names $DOPPLER_API_PARAM --with-decryption --query "Parameters[0].Value" --output text) 
export DOPPLER_API_TOKEN=$(aws ssm get-parameters --region $REGION --names $DOPPLER_CLIENT_PARAM --with-decryption --query "Parameters[0].Value" --output text) 

docker-compose -f $docker_compose_path up -d